global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['opentelemetry-collector:8888']
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092'] 
  - job_name: 'auth-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['auth-service:8088']
        labels:
          application: 'Auth Service Application'
  - job_name: 'product-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['product-service:8081']
        labels:
          application: 'Product Service Application'
  - job_name: 'order-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['order-service:8082']
        labels:
          application: 'Order Service Application'
  - job_name: 'email-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['email-service:8083']
        labels:
          application: 'Email Service Application'