{
 "title": "Prometheus",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Product Updated",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "product_updates_received_created",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Email Send Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "targets": [
    { "expr": "email_send_latency", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Auth Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    { "expr": "http_requests_created", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Order Create",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 25 },
   "targets": [
    { "expr": "orders_created_total", "legendFormat": "__auto" }
   ]
  }
 ]
}